5620: Moved Motion.get_units to genie_epics_api
ISISNeutronMuon/InstrumentScripts pull request #69
Opened 2020-08-20 16:00 UTC by mihai-stfc

### Instrument(s)

general/scans/motion.py

### Story/Acceptance criteria

- As an instrument scientist I want the units of a block to be accessible through the api, this is needed when creating graphs with units on (and probably other places too)

### Description of work

Units for a block are now accessible directly through the API.
Moved the `Motion/get_units` function to `genie_epics_api`, renamed to `get_block_units` to be used in `get_block_data` for `g.cget()` 

### Issue/Ticket Reference

https://github.com/ISISComputingGroup/IBEX/issues/5620

### Tests

Block units are displayed in the output dictionary from `g.cget("<blockname>")`

### To test

In IBEX GUI Scripting perspective run the `g.cget()` command on a block. The block's unit (if it has one) should be displayed under the value e.g. `('unit', 'Hz'),`. If block does not have a unit, it will be an empty string e.g `('unit', ''),`.

---

#### Code Review

- [ ] Is the story/acceptance criteria fulfilled?
- [ ] Is the code of an acceptable quality?
- [ ] Are the tests sufficient?
- [ ] Do the changes function as described and is it robust?
- [ ] Are the changes able to work across all intended instruments?

### Final Steps
- [ ] Are there any changes to instrument configurations required?
- [ ] Are there any changes to instrument scripts required, e.g. change on script signature, default argument and have these been communicated?
- [ ] Does the script need to be deployed onto the instrument?

2020-08-25 13:33 UTC, Alistair-McGann-Tessella requested changes

2020-08-25 13:33 UTC, Alistair-McGann-Tessella commented on general/scans/motion.py
> +        motion = BlockMotion(motion_or_block_name, g.cget(motion_or_block_name)["units"])
Can this not use your new method in genie python? I would expect this call to look something like g.get_block_units(block)

2020-09-07 14:45 UTC, JamesKingWork requested changes
We don't necessarily know that get_units is not used in some of the scientist/user scripts, it may be best to not remove the get_units method completely but make it an alias to g.get_block_units and mark it as deprecated

2020-09-07 15:13 UTC, JamesKingWork approved these changes

2020-09-07 15:13 UTC, merged