Handle invalid data point when appending to dataset
ISISNeutronMuon/InstrumentScripts pull request #86
Opened 2021-01-15 17:25 UTC by mihai-stfc

### Instrument(s)

Technique, Muon

### Story/Acceptance criteria

The background plot task does not fall over if it's save files are corrupted

### Description of work

Handle invalid data point when appending to dataset, set `run_numbers_match` to False on invalid `saved_run_number`/`current_run_number`, handle row index & datetime format errors.
Display corrupt file warnings and attempt to load and plot using the valid data from the file.

### Issue/Ticket Reference

https://github.com/ISISComputingGroup/IBEX/issues/5582

### Tests

Manual tests. 

### To test

[Background Script IOC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Background-Script-IOC)

Configuration, `background_script.py`, `init_<name>.py`, IOC logs and "corrupted" save file used for testing:
[Ticket5582.zip](https://github.com/ISISNeutronMuon/InstrumentScripts/files/5822006/Ticket5582.zip)

Run the background plot as normal via the `BGRSCRPT_01` IOC, check that the plot is working as intended.
Edit the `background_plot_data_01.csv` file to corrupt the data.
Restart IOC, make sure the dataset matches (`self.saved_data_matches_current_dataset()`) in `BackgroundPlot.start` so the script loads the save file instead of creating a new file.
Check that the IOC does not get stuck in a restart loop due to failing to load the save file.

---

#### Code Review

- [ ] Is the story/acceptance criteria fulfilled?
- [ ] Is the code of an acceptable quality?
- [ ] Are the tests sufficient?
- [ ] Do the changes function as described and is it robust?
- [ ] Are the changes able to work across all intended instruments?

### Final Steps
- [ ] Are there any changes to instrument configurations required?
- [ ] Are there any changes to instrument scripts required, e.g. change on script signature, default argument and have these been communicated?
- [ ] Does the script need to be deployed onto the instrument?

2021-01-18 17:03 UTC, RaiBishal requested changes
Looks good! however, we should start adding tests. I understand there are no tests currently for this module but we can start by adding couple for `load_data_from_save`.

2021-01-25 13:29 UTC, Tom-Willemsen requested changes

2021-01-25 13:29 UTC, Tom-Willemsen commented on technique/muon/tests/test_background_plot.py
> +        pass
remove `pass`

2021-01-25 13:29 UTC, Tom-Willemsen commented on technique/muon/tests/test_background_plot.py
> +        pass
remove this method if it doesn't do anything

2021-01-25 13:29 UTC, Tom-Willemsen commented on technique/muon/tests/data/corrupted_plot_data_01.csv
> +# run_number:00000039
Usually we shouldn't have large data files for a unit test.

Can you remove this and split the unit test you've added into separate tests for the different cases:
- Date format wrong
- No data present
- Wrong number of fields
- etc

2021-01-29 13:24 UTC, Tom-Willemsen approved these changes

2021-01-29 13:24 UTC, merged